### ISSUE TITLE
HumHub errors

### ISSUE THREAD

**Issue by D1reW0lf** [humhub-contrib/blog#8]
Hi all.

I apologize to bother since I'm quite aware that this is just an "non published", still on the beginning module.
I was looking for a blog solution for HumHub when I found out this module.
So I gave it a try, but since there where many errors, specially the "latest posts" side widget not working and throwing a lot of "LatestBlogStream" errors I decided to remove it.

But now, even after "uninstall -> remove" the module I still have a lot of critical errors like
Calling unknown method: humhub\modules\blog\Module::getPath()

Is there a way to fully remove whatever might still remain of the blog config on my server?

Thank you!
Pedro

> yii\base\UnknownMethodException: Calling unknown method: humhub\modules\blog\Module::getPath() in /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php:301 Stack trace: #0 /var/www/html/protected/humhub/modules/admin/controllers/ModuleController.php(192): yii\base\Component->__call() #1 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove() #2 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #3 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() #4 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction() #5 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction() #6 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest() #7 /var/www/html/index.php(25): yii\base\Application->run() #8 {main}

**Comment by luke-** [comment]
Try clearing the cache (Administration -> Settings -> Advanced -> Cache).

**Comment by D1reW0lf** [comment]
Thanks.
I did that and just in case deleted both /assets and /protected/runtime/cache.

Let's see what's going to happen. :)

**Comment by D1reW0lf** [comment]
Worked just fine.
Thank you for your help.
